### ISSUE TITLE
Smart Recommendations Error

### ISSUE THREAD

**Issue by tom5491** [psyko-gh/overcrawlrr#21]
Hello!

First off, really like what you've created, relatively straightforward to figure out for the most part. I've got the discovery working but not the smart recommendations (which I know is currently a WIP).

Is there anything you could suggest?

Thanks!

settings.yaml
```
config:
    overseerr:
        apiUrl: 
        user: 
        password: 
    discovery:
        # Required
        cron: '30 3 * * *'
        # Required - the overseer streams to search through
        # Possible values: upcoming, popular, trending
        streams:
            - upcoming
            - popular
            - trending
        ruleset: decent-scifi
    plex:
        apiUrl: 
        plexToken: 
    smartRecommendations:
        # Required
        cron: '40 3 * * *'
        # The name of the plex library to use as a seed
        plexLibrary: Films
        # Your minimum personal rating to consider
        minimumRating: 6.9
        ruleset: decent-scifi
        dryRun: true
    rulesets:
        - name: english-audio
          rules:
              - name: English Audio
                whenMatch:
                    - originalLanguage: en
                action: accept
        - name: decent-scifi
          rules:
              - name: Decent Films
                extends: english-audio
                whenMatch:
                    - and:
                        - genre:
                            - science-fiction
                            - action
                            - adventure
                            - animation
                        - score: above 6.5/10
                action: accept
```

This is what shows in the docker logs:
> [ 2024-09-03 10:50:19.239 ] info: Testing Plex connection...
[ 2024-09-03 10:50:19.244 ] info: ✔  Plex connection successful
[ 2024-09-03 10:50:30.811 ] info: Using ruleset: decent-scifi
TypeError: Cannot read properties of undefined (reading 'map')
    at PlexApi.<anonymous> (/app/api/plex/index.js:73:76)
    at Generator.next (<anonymous>)
    at fulfilled (/app/api/plex/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I did also try changing the name of the library to the folder name which is "films" but it couldn't find that so I guess it needs to be the actual library name in Plex:
> [ 2024-09-03 10:48:29.065 ] info: Testing Plex connection...
[ 2024-09-03 10:48:29.075 ] info: ✔  Plex connection successful
[ 2024-09-03 10:49:03.330 ] info: Using ruleset: decent-scifi
[ 2024-09-03 10:49:03.334 ] info: Cannot find Plex library 'films'. Stopping...
