### ISSUE TITLE
Support for Specifying Radarr/Sonarr Instance for Downloads in Multi-Instance Jellyseerr Setup

### ISSUE THREAD

**Issue by Chesyre** [psyko-gh/overcrawlrr#34]
Hi,

I am using Overcrawlrr to automate movie requests via rules and it has been very helpful. However, I have a multi-instance setup for Jellyseerr and I would like to know if it is possible to specify which Radarr or Sonarr instance should handle the download of a particular movie.

Currently, Overcrawlrr does not seem to have an option to direct requests to specific instances, which would be very useful in a multi-instance environment to better manage and distribute downloads.

Requested Feature:

An option in the rule configuration to specify the Radarr/Sonarr instance that should handle the request.
Integration with multi-instance Jellyseerr setups to ensure requests are sent to the correct instance.
Use Case: In a multi-instance setup, different instances may be configured for different genres, qualities, or sources. Being able to specify the instance would allow for more granular control over where movies are downloaded and how they are managed.

Expected Outcome:

A new field in the rule configuration UI where the user can select the specific Radarr/Sonarr instance.
Enhanced integration with Jellyseerr to support multi-instance configurations.
Thank you for considering this feature request!

Best regards,

**Comment by psyko-gh** [comment]
Hi,

You're right, Overcrawlrr only support a single Overseerr/Jellyseerr setup for now.
I'm quite confuse: do you have multiple Jellyseer instance, or multiple Radarr instances (or both) ?

So there are 2 requests:
1. feature 1: allow the configuration of multiple Jellyseerr servers,
2. feature 2: allow to specify which instance of Radarr to use in a specific Jellyseerr server

Is that correct ?

For the time being, Overcrawlrr does not support TV shows, so Sonarr is not yet relevant in this issue.

**Comment by destrodxbad** [comment]
I apologize for the confusion in my initial request. Let me clarify:
To be precise:

1. I have only one instance of Jellyseerr.
2. Within this single Jellyseerr instance, I have three different Radarr instances configured.

My request is specifically about the second feature you mentioned:

Feature 2: Allow specifying which Radarr instance to use within the single Jellyseerr server.

The reason for this setup is that I use different Radarr instances for different types of content. For example:

-One Radarr instance for documentaries
-Another Radarr instance for feature films

It would be very useful if Overcrawlrr could allow us to define a specific Radarr server for downloads based on rules. 
This way, we could automate requests to go to the appropriate Radarr instance based on the type of content.

**Comment by psyko-gh** [comment]
No worries, thx for the clarification.
Your request makes sense. I'm just wondering at which level should this be specified ?

- **at ruleset level**: the target Radarr to use would be configuring for an entire ruleset. Whenever a rule action is `accept`, the request would be made using the parent ruleset parameter. But this could be kind of problematic when a ruleset extends another.
- **at rule level**: each rule with an `accept` action could configure the target Radarr server. This would be the most flexible option, but also the most verbose.

Could you please share your rules configuration to show me on which basis you would made the decision of the Radarr server to chose ?

At the rule level, the setting could be something like:
```yml
  rules:
    - name: Acceptable sci-fi movie
      whenMatch:
        - genre:
            - science-fiction
        - score: above 5
      action: accept
      with:
        - radarr: the-name-of-the-instance
```

This feature might also be the opportunity to add a `4k` settings, since Overseerr (and probably Jellyseerr) supports 2 default Radarr server: one for 4K and one for non-4K

**Comment by destrodxbad** [comment]
I agree that implementing it at the rule level would be the most flexible way to go.

Here's my current config:

```yaml
config:
  overseerr:
    apiUrl: http://jellyseerr:5055/api/v1
    user: '****'
    password: '****'
    dryRun: false
  discovery:
    cron: '0 3 * * *'
    streams:
      - upcoming
      - popular
      - trending
    ruleset: films
  rulesets:
    - name: films
      extends: documentaires
      rules:
        - name: Accepter tous les films
          whenMatch:
            - adult: no
          action: accept
    - name: documentaires
      extends: spectacles
      rules:
        - name: Refuser les documentaires
          whenMatch:
            - genre:
                - Documentaire
          action: reject
    - name: spectacles
      rules:
        - name: Refuser les spectacles
          whenMatch:
            - keyword:
              - one-man show
              - one woman show
              - sketch
          action: reject
        - name: Refuser les films sans writer
          whenMatch:
              - crew:
                  job: Writer
                  names:
                    - "*"
          action: reject
```
          
Right now, as you can see, I've got a rule that accepts all movies and filters out documentaries and shows to download only movies.
